In [1]:
# import libraries
import numpy as np
import pandas as pd

In [2]:
# from sklearn import class, modules
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

# For the purpose of creating pipeline.
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [3]:
# train.csv
df = pd.read_csv('train.csv')
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)
df.head(2)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C

In [4]:
# Check for the missing values
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [5]:
# let plan
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']),
                                                   df['Survived'],
                                                    test_size=0.2,
                                                    random_state=42
                                                   )

In [6]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [7]:
y_train.sample(5)

708    1
745    0
789    0
784    0
873    0
Name: Survived, dtype: int64

In [8]:
# imputation transformer
trf1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy = 'most_frequent'), [6])]
                        , remainder='passthrough')

In [9]:
# OneHotEncoding
trf2 = ColumnTransformer(
    [
        (
            'ohe_sex_embarked', OneHotEncoder(
            sparse_output=False, handle_unknown='ignore'),
            [1,6]
        )
    ], remainder='passthrough'
)

In [10]:
# Scaling
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0, 10))
])

In [11]:
# Feature Selection
trf4 = SelectKBest(score_func=chi2, k=5)

In [12]:
# train the model
trf5 = DecisionTreeClassifier()

## *Create Pipeline*

In [13]:
pipe = Pipeline([
    ('trf1', trf1),
    ('trf2', trf2),
    ('trf3', trf3),
    ('trf4', trf4),
    ('trf5', trf5),
])

## *pipeline vs make_pipeline*
### pipeline requires naming of steps, make_pipeline does not.
### Same applies to column transformer vs make_column_transformer.

In [14]:
# Alternative Syntax
pipe = make_pipeline(trf1, trf2, trf3, trf4, trf5)

In [15]:
# Display pipeline

from sklearn import set_config
set_config(display = 'diagram')

In [16]:
# train
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x000001FFC2FD05E0>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

## *Explore the Pipeline*

In [17]:
# Code Here
pipe.named_steps['columntransformer-1'].transformers_[0][1].statistics_

array([29.49884615])

In [18]:
# predict 
y_pred = pipe.predict(X_test)

In [19]:
y_pred.shape

(179,)

In [20]:
# Calculating the accuracy of the model...
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6256983240223464

## *Cross validation Using Pipeline*

In [21]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.6391214419383433)

## *GridSearch Using Pipeline*

In [25]:
# gridsearchcv
params = {
    'columntransformer-5__max_depth': [1,2,3,4,5,None]
}

In [26]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

ValueError: Invalid parameter 'columntransformer-5' for estimator Pipeline(steps=[('columntransformer-1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('columntransformer-2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('columntransformer-3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('selectkbest',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x000001FFC2FD05E0>)),
                ('decisiontreeclassifier', DecisionTreeClassifier())]). Valid parameters are: ['memory', 'steps', 'transform_input', 'verbose'].

In [27]:
# best_score_
grid.best_score_

AttributeError: 'GridSearchCV' object has no attribute 'best_score_'

In [28]:
# best_params
grid.best_params

AttributeError: 'GridSearchCV' object has no attribute 'best_params'

## *Exporting the pipeline*

In [ ]:
# Export 
import pickle
pickle.dump(pipe, open('pipe.pk1', 'wb'))