In [2]:
# import libraries
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'], inplace=True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [ ]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# play or Not play

In [7]:
# Solution 

# P(Yes|Sunny, Hot, High, Weak) = P(Sunny|Yes)*P(Hot|Yes)*P(High|Yes)*P(Weak|Yes)

# P(No|Sunny, Hot, High, Weak) = P(Sunny|No)*P(Hot|No)*P(High|No)*P(Weak|No)

# Comapre a Maximum a posteriori rule.

In [ ]:
# Problem 2

# Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=Weak

In [ ]:
# Solution

# P(Yes|Overcast, Cold, Low, Weak) = P(Overcast|Yes)*P(Cold|Yes)*P(Low|Yes)*P(Weak|Yes)

# P(No|Overcast, Cold, Low, Weak) = P(Overcast|No)*P(Cold|No)*P(Low|No)*P(Weak|No)

# Comapre a Maximum a posteriori rule.

In [9]:
# Let find counts for play column.
data['play'].value_counts()

# Determine the priori probabilities
p_yes= 9/14
P_no= 5/14

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
# Now, let make crosstab for each column.
# Outlook
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
# let calculate conditional probalities for outlook
p_on = 0
p_rn = 2/5
p_sn = 3/5
p_oy = 4/9
p_ry = 3/9
p_sy = 2/9

In [11]:
# temp
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
# let calculate conditional probalities for temp
p_cn = 1/5
p_hotn = 2/5
p_mn = 2/5
p_cy = 4/9
p_hoty = 3/9
p_my = 2/9

In [12]:
# humidity
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
# let calculate conditional probalities for humidity.
p_highn = 4/5
p_nn = 1/5
p_highy = 3/9
p_ny = 6/9

In [13]:
# wind
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [ ]:
# let calculate conditional probalities for humidity.
p_strn = 4/5
p_weakn = 1/5
p_stry = 3/9
p_weaky = 6/9

## *Brut Force Code: Manual Way*

In [ ]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# play or Not play